services:
    data_collector.vcr:
        class:      VCR\VCRBundle\DataCollector\VCRDataCollector
        arguments:  [ @vcr.recorder ]
        tags:
            - { name: data_collector, template: "VCRVCRBundle:Profiler:collector", id: "vcr_collector" }

    vcr.config:
        class: VCR\Configuration
        calls:
            - [ setCassettePath, [ %vcr.cassette.path% ] ]
            - [ setStorage, [ %vcr.cassette.type% ] ]

    vcr.http_client:
        class: VCR\Util\HttpClient

    vcr.factory:
        class:          VCR\VCRFactory
        factory_class:  VCR\VCRFactory
        factory_method: getInstance
        arguments:      [ @vcr.config ]

    vcr.recorder:
        class:      VCR\VCRBundle\VCR\LoggedVideoRecorder
        arguments:  [ @vcr.config, @vcr.http_client, @vcr.factory ]
        calls:
            - [ turnOn, [ ] ]
            - [ insertCassette, [ %vcr.cassette.name% ] ]
